# Generated by Django 4.2.5 on 2023-09-08 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pokemon_entities",
            "0003_pokemonentity_defence_pokemonentity_health_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 8, 21, 18, 51, 778076)
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 8, 21, 18, 51, 778085)
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="lat",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="lon",
            field=models.FloatField(blank=True),
        ),
    ]
