# Generated by Django 4.2.5 on 2023-09-08 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0004_alter_pokemonentity_appeared_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 8, 21, 21, 0, 961960)
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 8, 21, 21, 0, 961971)
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
