# Generated by Django 4.2.5 on 2023-09-09 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0007_pokemon_title_en_pokemon_title_jp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="title_en",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title_jp",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 9, 7, 39, 15, 192204)
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 9, 7, 39, 15, 192214)
            ),
        ),
    ]
