# Generated by Django 4.2.5 on 2023-09-09 20:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "pokemon_entities",
            "0008_alter_pokemon_title_en_alter_pokemon_title_jp_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="next_evolution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_evolutions",
                to="pokemon_entities.pokemon",
            ),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="previous_evolution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="previous_evolutions",
                to="pokemon_entities.pokemon",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 9, 20, 8, 12, 872499)
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 9, 20, 8, 12, 872509)
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="pokemon",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pokemon",
                to="pokemon_entities.pokemon",
            ),
        ),
    ]
