# Generated by Django 4.2.5 on 2023-09-10 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pokemon_entities",
            "0009_pokemon_next_evolution_pokemon_previous_evolution_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokemon",
            name="next_evolution",
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 10, 18, 39, 23, 532602)
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 10, 18, 39, 23, 532612)
            ),
        ),
    ]
