# Generated by Django 4.2.5 on 2023-09-16 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pokemon_entities",
            "0012_alter_pokemon_options_alter_pokemonentity_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="desciption",
            field=models.TextField(
                blank=True, default="", max_length=1000, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Название на английском",
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title_jp",
            field=models.TextField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Название на японском",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 16, 22, 56, 18, 560473),
                verbose_name="Когда появился",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 16, 22, 56, 18, 560482),
                verbose_name="Когда исчез",
            ),
        ),
    ]
