# Generated by Django 4.2.5 on 2023-09-16 23:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0014_alter_pokemon_previous_evolution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 16, 23, 4, 25, 747170),
                verbose_name="Когда появился",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 16, 23, 4, 25, 747180),
                verbose_name="Когда исчез",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="pokemon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pokemon_species",
                to="pokemon_entities.pokemon",
                verbose_name="Покемон",
            ),
        ),
    ]
