# Generated by Django 4.2.5 on 2023-09-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0015_alter_pokemonentity_appeared_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(verbose_name="Когда появился"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(verbose_name="Когда исчез"),
        ),
    ]
