# Generated by Django 4.2.5 on 2023-09-17 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0016_alter_pokemonentity_appeared_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="desciption",
            field=models.TextField(
                blank=True, max_length=1000, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Название на английском"
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title_jp",
            field=models.TextField(
                blank=True, max_length=50, verbose_name="Название на японском"
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="pokemon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pokemon_entity",
                to="pokemon_entities.pokemon",
                verbose_name="Покемон",
            ),
        ),
    ]
