# Generated by Django 4.2.5 on 2023-09-17 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "pokemon_entities",
            "0017_alter_pokemon_desciption_alter_pokemon_title_en_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonentity",
            name="pokemon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to="pokemon_entities.pokemon",
                verbose_name="Покемон",
            ),
        ),
    ]
